### ISSUE TITLE
python3.9 seems to be broken in GHA

### ISSUE THREAD

**Issue by webknjaz** [deadsnakes/issues#138]
### description

It looks like
```yaml
- uses: deadsnakes/action@v1.0.0
  with:
    python-version: 3.9
```
is no longer able to install CPython 3.9. See the log: https://github.com/pypa/setuptools/runs/1239723861#step:4:212

_P.S. I haven't attempted to debug this, just saw it accidentally and thought I'd report this at least._

#### lsb_release -a

Ubuntu 20.04 (but not sure if others are affected)

#### uname -a

N/A
