### ISSUE TITLE
Add Example Ansible Playbook to Documentation

### ISSUE THREAD

**Issue by cooperlees** [deadsnakes/issues#154]
### description

I couldn't see if there is somewhere accessible for me to add an example ansible playbook  to deadsnakes documentation. Is there any interest? If not, just close. All good.

```yaml
---
  - name: Add Deadsnakes Nightly APT repository
    apt_repository:
      repo: ppa:deadsnakes/nightly
    when: ansible_distribution_release in ["focal", "bionic", "xenial"]

  - name: Install latest pythons
    apt:
      name: ['python3.9-dev', 'python3.9-venv', 'python3.10-dev', 'python3.10-venv']
      state: latest
      update_cache: yes
    when: ansible_distribution_release in ["focal", "bionic", "xenial"]
```
