### ISSUE TITLE
Installing into a non-Python Travis CI repo provides neither pip nor ensurepip

### ISSUE THREAD

**Issue by cclauss** [deadsnakes/issues#70]
On a normal __Travis CI Trusty worker__ where the project is NOT a Python project...

```
language: go  # <<< Note: This is NOT Python!
sudo: required

addons:
  apt:
    sources: deadsnakes
    update: true
    packages:
      - python3.6
 
before_script:
  - python3.6 --version
  # - python3.6 -m pip --version             # <<< fails
  # - sudo python3.6 -m ensurepip --upgrade  # <<< fails
  - python3.6 -m venv env --without-pip
  - source env/bin/activate
  - curl https://bootstrap.pypa.io/get-pip.py | python3.6
  - python3.6 -m pip --version
  - python3.6 -m pip --install --upgrade pip

script: true
```

* Why not include __pip__ in the __python3.6__ package?
* Why not include __ensurepip__ in the __python3.6__ package?
* Why no __python3.6-pip__ package similar to the standard __python3-pip__ package?
* Is the __venv --> get-pip.py__ approach above the best way to go?
* The above will NOT work on Python 3.7 for the SSL reasons discussed at https://github.com/travis-ci/travis-ci/issues/9069
